### ISSUE TITLE
Klaro does not recognize the browser language

### ISSUE THREAD

**Issue by shi-rudo** [lazybytez/gatsby-plugin-klaro#13]
**Describe the bug:**  
❌ In development mode `gatsby develop` Klaro.js does not recognize the respective language in the `<html lang="xy">`. If Klaro.js is included manually, without the plugin, this works. 

✅ In production mode `gatsby build` with `gatsby serve` the plugin/Klaro recognizes the correct language. 

**Screenshot:**  
![screenshot](http://www.dlds.de/pub/klaro/lang-klaro-de.jpg)

**Expected behavior:**  
It should detect the correct html lang in development mode.

**Platform (please complete the following information):**  
 - OS: osx 10.15.7, Klaro v.0.7.18, gatsby-plugin-klaro v.1.0.1

**Comment by shi-rudo** [comment]
A minimal working example showing the error can be found here:
https://github.com/shi-rudo/klaro-intl

**Comment by pascal-zarrad** [comment]
@shi-rudo Thank you for your bug report! I will investigate, verify and fix the issue within the next days.

**Comment by shi-rudo** [comment]
any news?

**Comment by pascal-zarrad** [comment]
Did not have the time to check it until now. Will check it today.

**Comment by pascal-zarrad** [comment]
I now checked the issue and can verify that Klaro is always english in the developer mode. In the production mode it works as expected.

Right now it's unclear how the issue can be fixed. I will further investigate if there is some working fix in the development mode. But I don't think hotreload will work properly with Klaro out of the box. So even if the translations work, we might still have to totally reload the page in the development process.

**Comment by shi-rudo** [comment]
I appreciate the work you put into writing the plugin 👍. But what use has the plugin it if a large part of the features do not work or are not supported. It is possible to inject klaro.js into the header without the plugin, this is not the perfect solution, but it works.

**Comment by pascal-zarrad** [comment]
Hi,

we internally decided to abandon this project. There won't be any future updates from our side and the repository will be archived.
If you like, you can checkout [gatsby-plugin-tagmanager](https://github.com/lazybytez/gatsby-plugin-tagmanager) as an alternative to include the Klaro tag and configuration in your project.
