### ISSUE TITLE
Contextual consent screen should stay visible on load and reload

### ISSUE THREAD

**Issue by shi-rudo** [lazybytez/gatsby-plugin-klaro#14]
**Describe the bug:**  
Contextual consent does not display

**To Reproduce:**  
❌ In development mode `gatsby develop` Klaro.js does not properly store the contextual consent
❌ In production mode contextual consent does also not work as expected

**Expected behavior:**  
* Contextual consent should be stored on dev mode.
* Contextual consent screen should be visible in dev mode.

It does work as expected when injecting klaro.js into the header by hand. Using the plugin does produce the errors above:

**Screenshots:**  
Please see the video:
[![video](https://j.gifs.com/mOl1DR.gif)](https://youtu.be/JSjZAfDXrjU)
full video: https://youtu.be/JSjZAfDXrjU

**Platform (please complete the following information):**  
 - OS: osx 10.15.7, Klaro v.0.7.18, gatsby-plugin-klaro v.1.0.1, safari version 14.0.3, chrome version 89.0.4389.114 

**Additional context:**  

A minimal working example showing the error can be found here:
https://github.com/shi-rudo/klaro-intl

**Comment by pascal-zarrad** [comment]
Hi,

we internally decided to abandon this project. There won't be any future updates from our side and the repository will be archived.
If you like, you can checkout [gatsby-plugin-tagmanager](https://github.com/lazybytez/gatsby-plugin-tagmanager) as an alternative to include the Klaro tag and configuration in your project.
